source 'https://rubygems.org'

ruby ">= 2.6.10"

# Exclude CocoaPods releases that break React Native builds.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 7.2.3.1', '< 8'
