version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    groups:
      dev-dependencies:
        patterns:
          - '*'
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'patch'
    ignore:
      # Ignore major version updates for React Native
      - dependency-name: 'react-native'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'

  # Enable security updates for npm in example app
  - package-ecosystem: 'npm'
    directory: '/example'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'example'
    groups:
      example-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
