version: 2

# GitHub requires at least one update configuration
# Setting open-pull-requests-limit to 0 effectively disables version updates
# but still allows security updates to come through
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    # Set to 0 to only get security updates
    open-pull-requests-limit: 0
    labels:
      - 'security'
      - 'dependencies'
